AllCops:
  Include:
    - '**/Rakefile'
    - lib/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier: 
  Enabled: false

Metrics/AbcSize:
  Max: 16

Layout:
  Enabled: false

Style:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: false